#!/bin/bash

echo "📤 JAVELIN SECURITY - IMAGE UPLOAD HELPER"
echo "=========================================="
echo ""
echo "Follow these steps:"
echo ""
echo "1️⃣  Upload your images to VS Code:"
echo "   - Open VS Code file explorer (left sidebar)"
echo "   - Right-click on '/workspaces/Javelin' folder"
echo "   - Select 'Upload Files...'"
echo "   - Select your 6 images"
echo ""
echo "2️⃣  After upload, run:"
echo "   chmod +x fix-images-now.sh"
echo "   ./fix-images-now.sh"
echo ""
echo "3️⃣  Start the app:"
echo "   cd client && npm start"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Current images in project:"
find /workspaces/Javelin -maxdepth 3 -type f \( -iname "*.jpg" -o -iname "*.png" \) 2>/dev/null | grep -v node_modules | head -20
echo ""
